### PR TITLE
Steps component

### PR DESCRIPTION
**Pull request by alexcss**
## Description

* Steps component

## Screenshots/GIFs

image

## Checklist

- [x] I have read and understood the contributing guidelines.
- [x] I have followed the style guide and formatting guidelines.
- [x] I have added appropriate comments to explain the changes.
- [x] I have tested my changes thoroughly.

### CODE REVIEW

**Review by owans — APPROVED** [review]
LGTM!

**Comment by owans** [comment]
Please resolve conflict @alexcss. Thank you

**Comment by alexcss** [comment]
> Please resolve conflict @alexcss. Thank you

@owans done

**Comment by owans** [comment]
> > Please resolve conflict @alexcss. Thank you
> 
> @owans done

Thank you

**Pull request merged**
