### PR TITLE
Dev api docs fix param for getbalance example script

### LINKED ISSUE #106: getBalance script example 1 has the wrong input param
Script example 1 (https://github.com/rsksmart/devportal/blob/42fdd270885a6fa472e12c0bd3db4b269bbb40b3/docs/02-developers/07-rpc-api/02-methods.md?plain=1#L208) claims to use a blockNumber for the second param, while example 2 claims to use a blockHash and example 3 claims to use a blockTag. Script examples 2 and 3 correctly use the params they claim to, but example 1 erroneously had a blockTag instead of a blockHash

### PR DESCRIPTION
**Pull request by RedVelvetZip**
[Issue #106](https://github.com/rsksmart/devportal/issues/106)

### CODE REVIEW

**Comment by owans** [comment]
Thank you for submitting this PR @RedVelvetZip. 

@ivegabr Please review and approve this change. Thank you.

**Review by ivegabr — APPROVED** [review]
ok

**Review by ivegabr — APPROVED** [review]
ok

**Review by ivegabr — APPROVED** [review]

**Review by ivegabr — APPROVED** [review]
ok

**Comment by owans** [comment]
Thank you @RedVelvetZip for submitting this fix.

**Review by owans — APPROVED** [review]
LGTM!

**Pull request merged**
