### PR TITLE
News announcement bar

### PR DESCRIPTION
**Pull request by alexcss**
## Description

* News bar hides/shows on page scroll
* Closed state stored in session
* News title is limited by 150 chars
* News data are stored in `docusaurus.config.js` in `customFields`:
````
const config = {
...
  customFields : {
    ...
   newsHighlight : [
      {
        title : '📣 Rootstock Hacktivator Program is Live! Contribute and Earn Rewards!',
        url : '/resources/contribute/hacktivator-program/'
      }
    ]
  }
...
}
```` 

## Screenshots/GIFs

image

## Checklist

- [x] I have read and understood the contributing guidelines.
- [x] I have followed the style guide and formatting guidelines.
- [x] I have added appropriate comments to explain the changes.
- [x] I have tested my changes thoroughly.

### CODE REVIEW

**Review by owans — APPROVED** [review]
LGTM!

**Comment by owans** [comment]
Looks good. Could we add a small padding between the "Rootstock and the announcement" on mobile?

IMG_4627

**Comment by alexcss** [comment]
@owans Do you mean add padding here?

image

**Comment by owans** [comment]
Yes, just a little padding @alexcss

**Comment by alexcss** [comment]
@owans done 👌

**Comment by owans** [comment]
> @owans done 👌

Thank you

**Pull request merged**
