### PR TITLE
Create glossary.md

### PR DESCRIPTION
**Pull request by wise4rmgodroot**
## Title
* Rootstock Glossary

## Description

* I added added some important terms related to Rootstock on the glossary page.

### CODE REVIEW

**Review by owans — COMMENTED** [review]
Please move Glossary to Concepts bucket

**Review by owans — COMMENTED** [review]
Use the Button component for all the related links or resources for each term.

Also use a descriptive Title for the buttons, for better SEO and communication to the user.

Instead of [Account Abstraction]()

Do [Get started with Account Abstraction on Rootstock]

**Comment by wise4rmgodroot** [comment]
Search engines don't go through buttons, its better to use the HTML ref <a> or markdown ref []() which any search engine can easily crawl and index.

**Comment by owans** [comment]
We should use the `<a>` attribute then. Give that feedback to Zgraya too.

The titles are still not optimized though

And also the page not been moved to Concepts bucket

@wise4rmgodroot

**Comment by owans** [comment]
Related to #181

**Pull request closed without merging**
