### PR TITLE
2wp-app v2.0

### PR DESCRIPTION
**Pull request by alexjavabraz**
- 2wp-app version 2.0
- new look and feel
- light and dark themes
- liquality removal

### CODE REVIEW

**Review by owans — COMMENTED** [review]
- Added commit to fix broken link in pegin status
- Minor fixes in ref to liquality in peg in with leather

**Comment by owans** [comment]
@alexjavabraz No support for Peg out with Leather yet?

**Comment by alexjavabraz** [comment]
> @alexjavabraz No support for Peg out with Leather yet?

Not yet.

**Comment by owans** [comment]
Ok. Cool

**Pull request merged**
